Refactor upgrade test
terraform-ibm-modules/ibmcloud-terratest-wrapper pull request #606
Opened 2023-08-17 09:40 UTC by daniel-butler-irl

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-08-17 15:23 UTC, daniel-butler-irl commented
/run pipeline

2023-08-17 15:25 UTC, daniel-butler-irl commented
Working locally, I'm just not 100% sure how it will act in the pipelines. I hope it will "just work", but may need to set some extra variables for the git clone

2023-08-22 09:08 UTC, daniel-butler-irl commented
/run pipeline

2023-08-22 10:13 UTC, daniel-butler-irl commented
/run pipeline

2023-08-22 11:50 UTC, daniel-butler-irl commented
/run pipeline

2023-08-22 12:26 UTC, daniel-butler-irl commented
/run pipeline

2023-08-22 14:48 UTC, daniel-butler-irl commented
/run pipeline

2023-08-22 20:50 UTC, toddgiguere requested changes

2023-08-22 20:50 UTC, toddgiguere commented on testhelper/test_options.go
> +	BaseGitPrivateSshKey string
This is incredibly risky for a user. I personally would never set either PAT or a private key in code. You could eliminate these two and just rely on ENV variables? would be a lot safer I think.

2023-08-23 08:54 UTC, daniel-butler-irl commented
/run pipeline

2023-08-23 09:28 UTC, merged

2023-08-23 09:30 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.11.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/releases/tag/v1.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: