[WIP] feat: skip destroy for schematics resources
terraform-ibm-modules/ibmcloud-terratest-wrapper pull request #703
Opened 2023-11-27 08:16 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-27 08:17 UTC, Aashiq-J commented
/run pipeline

2023-11-27 16:38 UTC, toddgiguere requested changes

2023-11-27 16:38 UTC, toddgiguere commented on testschematic/tests.go
> +func (options *TestSchematicOptions) RunSchematicTest() (*SchematicsTestService, error) {
I'm not sure this change (creating package global for the service pointer and returning it from the Run function) is necessary. The original design was to create a new service object, only if not initially provided in options struct, and then store that pointer in the options struct to be used later if needed. 

The change that is likely needed here would be to make `options.schematicsTestSvc` a public struct attribute by capatalizing the name: `options.SchematicsTestSvc`. By making that attribute public you can then reference it inside this package AND outside in the terraform unit test, and avoid having a package global containing a pointer (which is sometimes avoided due to complexity).

I would remove the global `svc`, remove the return value, and just change the options attribute to public (simply capatalize the attribute name).

2023-11-27 16:38 UTC, toddgiguere commented on testschematic/tests.go
> -	if svc.TerraformResourcesCreated {
If you are moving the resource destroy from this block, you need to still replace it with your new TestTearDown() or similar.

Keep in mind thought that in this test case there are TWO different destroy that take place:
1. The destroy of the applied resources
2. The delete of the workspace

The block removed here is covering item 1, the destroy of the applied resources, NOT the deletion of the workspace.

Perhaps a short meeting or slack conversation can explain this better.

2023-11-27 18:03 UTC, toddgiguere requested changes

2023-11-27 18:03 UTC, toddgiguere commented on testschematic/test_options.go
> +	newOptions.SkipTestTearDown = false
should only default to false if the value is not set in originalOptions (if it is set to true).

In golang, the default for a bool is already false, so setting this here is probably optional.

2023-11-28 11:51 UTC, Aashiq-J commented
/run pipeline

2023-12-11 11:51 UTC, ocofaigh commented
@toddgiguere @Aashiq-J Did we decide we still proceed with these changes?

2024-05-13 14:06 UTC, toddgiguere requested changes

2024-05-13 14:06 UTC, toddgiguere commented on testschematic/tests.go
> +	options.SchematicsTestSvc = svc
This should be higher up in the function and not left this late. Ideally you would set the options pointer for the service right after it is initialized on line 31. If the service was already set in the options (line 33) then it does not need to be reassigned.

2024-05-13 14:06 UTC, toddgiguere commented on testschematic/tests.go
> +func (options *TestSchematicOptions) testTearDownResources() {
If tear down of resources is private function (cannot be called outside of this package), then it shouldn't be a method on "options" it should be a method on SchematicsTestService.

2025-02-20 17:22 UTC, closed without merging