docs: example to test output value
terraform-ibm-modules/ibmcloud-terratest-wrapper pull request #772
Opened 2024-03-08 13:52 UTC by rajatagarwal-ibm

### Description

Example to test the output value.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-08 13:52 UTC, rajatagarwal-ibm commented
/run pipeline

2024-03-08 13:55 UTC, rajatagarwal-ibm commented
/run pipeline

2024-03-08 14:00 UTC, daniel-butler-irl commented on README.md
> +
I want to add some context here
> After the test completes and teardown occurs, the state file will no longer contain the outputs. To handle this the last test to execute stores its outputs in `LastTestTerraformOutputs`. There is also a helper function to validate that the outputs exist called `ValidateTerraformOutputs` this returns a list of output keys that are missing and an error message with details of the missing keys.

2024-03-08 14:04 UTC, rajatagarwal-ibm commented
/run pipeline

2024-03-08 14:08 UTC, SirSpidey requested changes
minor editorial suggestions.

2024-03-08 14:08 UTC, SirSpidey commented on README.md
> +After the test completes and teardown occurs, the state file will no longer contain the outputs. To handle this the last test to execute stores its outputs in `LastTestTerraformOutputs`. There is als
```suggestion
After the test completes and teardown occurs, the state file no longer contains the outputs. To handle this situation, the last test to execute stores its outputs in `LastTestTerraformOutputs`. Use the helper function called `ValidateTerraformOutputs` to validate that the outputs exist. The function returns a list of output keys that are missing and an error message with details.
```

2024-03-08 14:11 UTC, rajatagarwal-ibm commented
/run pipeline

2024-03-08 14:12 UTC, daniel-butler-irl approved these changes

2024-03-08 14:15 UTC, SirSpidey approved these changes
👍

2024-03-08 14:17 UTC, merged

2024-03-09 00:06 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.29.6 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/releases/tag/v1.29.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: